(lang dune 3.11)

(name ocaml_to_c)

(generate_opam_files true)

(package
 (name ocaml_to_c)
 (depends ocaml dune))

; See the complete stanza docs at https://dune.readthedocs.io/en/stable/dune-files.html#dune-project
